added commits
OWASP-BLT/BLT-Sammich pull request #17
Opened 2024-06-27 03:52 UTC by Sarthak5598

2024-06-28 17:41 UTC, arkid15r commented on pyproject.toml
> +ruff = "^0.4.8"
These should be in `test` dependency group so you'd be able to use `poetry install --with test`

2024-06-29 19:01 UTC, arkid15r requested changes
Please make sure the tests are running and don't fail

2024-06-29 19:49 UTC, Sarthak5598 commented
![image](https://github.com/OWASP-BLT/BLT-Sammich/assets/108613416/61b5ef10-6fad-4f2f-ac08-8fa49b6c9d86)
tests are fine now ,also corrected the ci-cd file

2024-06-30 00:25 UTC, arkid15r approved these changes
Looks good 👍

2024-06-30 03:01 UTC, Sarthak5598 commented
Thank you!

2024-06-30 03:01 UTC, merged